name: "Plan (post)"

on:
  workflow_run:
    workflows:
      - Plan
    types:
      - completed

jobs:
  notify:
    permissions:
      actions: read
      statuses: write
    name: "Notify"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sha="$(gh api '/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/jobs' --jq '.jobs[] | .steps[] | .name | select(startswith("Run sha="))')"
          sha="${sha#Run sha=}"
          gh api "repos/${{ github.repository }}/statuses/$sha" -f context='Plan' -f state='${{ github.event.workflow_run.conclusion }}' -f target_url='${{ github.event.workflow_run.html_url }}'
